### ISSUE TITLE
CPAN modules installed via Debian packages aren't listed anymore

### ISSUE THREAD

**Issue by joenio** [tokuhirom/cpan-outdated#29]
After commit 745deb that includes "ExtUtils::Installed", the CPAN modules installed on my Debian system aren't listed by cpan-outdated, even when these modules are outdated.

This behavior is expected?

**Comment by miyagawa** [comment]
It is expected, if the debian system doesn't install the packlist like regular CPAN install does. There's a suggestion to add an option to ignore packlists and fall back to a slow listing of all modules installed, but that hasn't been in place.
