### ISSUE TITLE
Latest version doesn't find everything

### ISSUE THREAD

**Issue by zdm** [tokuhirom/cpan-outdated#33]
For example, cpan-outdated-coro find, that Pod::Usage (new version 1.69 was released yesterday) is outdated, but cpan-outdated - not.

**Comment by syohex** [comment]
This issue is already fixed in master branch however it is not released yet.

**Comment by zdm** [comment]
Thank you.

**Comment by dolmen** [comment]
The latest code on the master branch has been released: [DOLMEN/cpan-outdated-0.30.tar.gz](https://metacpan.org/release/DOLMEN/cpan-outdated-0.30). There was an CPAN indexing problem for some weeks, but this is now fixed.

cpan-outdated 0.30 properly reports M/MA/MAREKR/Pod-Usage-1.69.tar.gz on my perl where Pod::Usage 1.67 is installed.

@zdm: can you confirm this is fixed?

**Comment by dolmen** [comment]
Oh, I have committed 0609506e96367e632b71ef79a917619b85aede09 since 0.30.

So @syohex is right. I have to make another release.

**Comment by syohex** [comment]
Please upgrade to 0.31. Thanks for reporting issue.
